# Generated by Django 2.0.9 on 2018-11-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('reg', models.ForeignKey(null=True, on_delete='CASCADE', to='application.Reg')),
            ],
        ),
    ]
