# Generated by Django 2.0.9 on 2018-11-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='reg',
        ),
        migrations.AddField(
            model_name='event',
            name='contact_no',
            field=models.CharField(default='3131313131', max_length=20, unique=True),
        ),
    ]
