# Generated by Django 2.0.9 on 2018-11-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20181114_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
