# Generated by Django 2.0.9 on 2018-11-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20181114_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='contact_no',
            new_name='contact',
        ),
    ]
