# Generated by Django 2.0.9 on 2018-11-14 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20181114_2352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
