# Generated by Django 2.0.9 on 2018-11-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.CharField(max_length=100)),
                ('event', models.CharField(max_length=30)),
            ],
        ),
    ]
