# Generated by Django 2.0.9 on 2018-11-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Querry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=20)),
                ('querry', models.CharField(max_length=500)),
            ],
        ),
    ]
