# Generated by Django 2.0.9 on 2018-11-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_event_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reg',
            field=models.ForeignKey(on_delete='CASCADE', to='application.Reg'),
        ),
    ]
