# Generated by Django 2.0.9 on 2018-11-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_auto_20181120_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(default='Btech', max_length=100)),
                ('college', models.CharField(default='BCET Gurdaspur', max_length=500)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contact_no', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='college',
        ),
        migrations.RemoveField(
            model_name='event',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='event',
            name='course',
        ),
        migrations.RemoveField(
            model_name='event',
            name='email',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='password',
        ),
    ]
